const STORAGE_KEY = 'whisk-recipes-v1';
const starterRecipes = [
 {id:'seed-1',name:'Avocado toast with herbs',category:'Breakfast',time:10,image:'',ingredients:['2 slices sourdough bread','1 ripe avocado','1 tsp lemon juice','Chilli flakes','Fresh herbs','Salt and pepper'],instructions:['Toast the sourdough until golden.','Mash avocado with lemon juice, salt, and pepper.','Spread over toast and finish with herbs and chilli flakes.'],created:Date.now()-5000},
 {id:'seed-2',name:'Creamy tomato pasta',category:'Dinner',time:25,image:'',ingredients:['200 g pasta','1 cup cherry tomatoes','2 garlic cloves','½ cup cream','Olive oil','Parmesan and basil'],instructions:['Cook pasta in salted water until al dente.','Sauté garlic and tomatoes in olive oil until soft.','Stir in cream and a splash of pasta water.','Toss with pasta and finish with parmesan and basil.'],created:Date.now()-4000},
 {id:'seed-3',name:'Berry breakfast bowl',category:'Breakfast',time:8,image:'',ingredients:['¾ cup thick yogurt','½ cup mixed berries','¼ cup granola','1 tsp honey','Chia seeds'],instructions:['Spoon yogurt into a bowl.','Arrange berries and granola on top.','Drizzle with honey and sprinkle with chia seeds.'],created:Date.now()-3000},
 {id:'seed-4',name:'Golden roasted vegetables',category:'Lunch',time:35,image:'',ingredients:['1 sweet potato','1 zucchini','1 red bell pepper','1 tbsp olive oil','Paprika','Salt and pepper'],instructions:['Heat oven to 220°C.','Chop vegetables into similar-sized pieces.','Toss with oil and seasoning.','Roast for 25–30 minutes, turning once.'],created:Date.now()-2000},
 {id:'seed-5',name:'Chocolate mug cake',category:'Dessert',time:5,image:'',ingredients:['4 tbsp flour','2 tbsp cocoa powder','2 tbsp sugar','3 tbsp milk','1 tbsp oil','¼ tsp baking powder'],instructions:['Mix all ingredients in a microwave-safe mug until smooth.','Microwave for 60–90 seconds, checking as it cooks.','Let cool briefly before enjoying.'],created:Date.now()-1000},
 {id:'seed-6',name:'Crispy masala chickpeas',category:'Snacks',time:30,image:'',ingredients:['1 can chickpeas, drained','1 tsp olive oil','½ tsp cumin','½ tsp paprika','¼ tsp turmeric','Salt to taste'],instructions:['Pat chickpeas dry and heat oven to 200°C.','Toss chickpeas with oil and spices.','Bake for 25–30 minutes, shaking the tray halfway through.','Cool slightly for extra crunch.'],created:Date.now()}
];
let recipes = loadRecipes(); let activeCategory='All'; let toastTimer;
const $=id=>document.getElementById(id);
function loadRecipes(){try{const data=JSON.parse(localStorage.getItem(STORAGE_KEY));return Array.isArray(data)?data:starterRecipes.map(x=>({...x}));}catch{return starterRecipes.map(x=>({...x}));}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(recipes));}
function escapeHTML(value=''){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function categoryEmoji(category){return ({Breakfast:'🥑',Lunch:'🥗',Dinner:'🍝',Dessert:'🍰',Snacks:'🥨'})[category]||'🍽️';}
function filteredRecipes(){const query=$('searchInput').value.trim().toLowerCase();let list=recipes.filter(r=>(activeCategory==='All'||r.category===activeCategory)&&(!query||`${r.name} ${r.category} ${r.ingredients.join(' ')}`.toLowerCase().includes(query)));const sort=$('sortSelect').value;if(sort==='az')list.sort((a,b)=>a.name.localeCompare(b.name));else if(sort==='time')list.sort((a,b)=>a.time-b.time);else list.sort((a,b)=>b.created-a.created);return list;}
function render(){const list=filteredRecipes();$('recipeGrid').innerHTML=list.map(r=>`<article class="recipe-card" tabindex="0" role="button" aria-label="View ${escapeHTML(r.name)}" data-open="${escapeHTML(r.id)}"><div class="card-image">${r.image?`<img src="${escapeHTML(r.image)}" alt="${escapeHTML(r.name)}" loading="lazy" onerror="this.remove()">`:`<span class="card-emoji">${categoryEmoji(r.category)}</span>`}<span class="category-pill">${escapeHTML(r.category.toUpperCase())}</span></div><div class="card-body"><div class="card-title-row"><h3 class="card-title">${escapeHTML(r.name)}</h3><button class="card-menu" aria-label="Open recipe options" data-options="${escapeHTML(r.id)}">•••</button></div><p class="card-description">${escapeHTML(r.ingredients.slice(0,3).join(' · '))}</p><div class="card-meta"><span class="time-meta">◷ &nbsp;${r.time} min</span><span class="view-link">View recipe ↗</span></div></div></article>`).join('');$('emptyState').hidden=list.length!==0;$('recipeCount').textContent=list.length;$('allCount').textContent=recipes.length;$('sectionTitle').childNodes[0].textContent=activeCategory==='All'?'All recipes':activeCategory;$('crumb').textContent=activeCategory.toUpperCase();$('clearSearch').hidden=!$('searchInput').value;document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.category===activeCategory));}
function showToast(message){const el=$('toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2400);}
function openForm(recipe=null){$('recipeForm').reset();$('recipeId').value=recipe?.id||'';$('formTitle').textContent=recipe?'Edit recipe':'A new favorite';if(recipe){$('recipeName').value=recipe.name;$('recipeCategory').value=recipe.category;$('recipeTime').value=recipe.time;$('recipeImage').value=recipe.image||'';$('recipeIngredients').value=recipe.ingredients.join('\n');$('recipeInstructions').value=recipe.instructions.join('\n');}$('formModal').hidden=false;setTimeout(()=>$('recipeName').focus(),50);}
function openDetail(id){const r=recipes.find(x=>x.id===id);if(!r)return;$('detailContent').innerHTML=`<div class="detail-hero">${r.image?`<img src="${escapeHTML(r.image)}" alt="${escapeHTML(r.name)}" onerror="this.remove()">`:`<span>${categoryEmoji(r.category)}</span>`}</div><div class="detail-category">${escapeHTML(r.category.toUpperCase())}</div><h2 class="detail-title" id="detailTitle">${escapeHTML(r.name)}</h2><div class="detail-time">◷ &nbsp; ${r.time} minutes &nbsp; · &nbsp; ${r.ingredients.length} ingredients</div><div class="detail-columns"><section><h3>Ingredients</h3><ul>${r.ingredients.map(x=>`<li>${escapeHTML(x)}</li>`).join('')}</ul></section><section><h3>Method</h3><ol>${r.instructions.map(x=>`<li>${escapeHTML(x)}</li>`).join('')}</ol></section></div><div class="detail-actions"><button data-edit="${escapeHTML(id)}">✎ Edit recipe</button><button class="delete-action" data-delete="${escapeHTML(id)}">Delete</button></div>`;$('detailModal').hidden=false;}
function closeModal(id){$(id).hidden=true;}
function deleteRecipe(id){const r=recipes.find(x=>x.id===id);if(!r)return;if(!confirm(`Delete “${r.name}” from your cookbook?`))return;recipes=recipes.filter(x=>x.id!==id);save();closeModal('detailModal');render();showToast('Recipe deleted');}
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>{activeCategory=b.dataset.category;render();}));['addButton','addTop','emptyAdd'].forEach(id=>$(id).addEventListener('click',()=>openForm()));$('searchInput').addEventListener('input',render);$('sortSelect').addEventListener('change',render);$('clearSearch').addEventListener('click',()=>{$('searchInput').value='';render();});
$('recipeForm').addEventListener('submit',e=>{e.preventDefault();const id=$('recipeId').value;const recipe={id:id||`recipe-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,name:$('recipeName').value.trim(),category:$('recipeCategory').value,time:Number($('recipeTime').value),image:$('recipeImage').value.trim(),ingredients:$('recipeIngredients').value.split('\n').map(x=>x.trim()).filter(Boolean),instructions:$('recipeInstructions').value.split('\n').map(x=>x.trim()).filter(Boolean),created:id?(recipes.find(r=>r.id===id)?.created||Date.now()):Date.now()};if(!recipe.name||!recipe.ingredients.length||!recipe.instructions.length||!Number.isFinite(recipe.time)||recipe.time<1){showToast('Please complete all required fields');return;}if(id)recipes=recipes.map(r=>r.id===id?recipe:r);else recipes.unshift(recipe);save();closeModal('formModal');activeCategory='All';render();showToast(id?'Recipe updated':'Recipe saved to your cookbook');});
document.addEventListener('click',e=>{const close=e.target.closest('[data-close]');if(close){closeModal(close.dataset.close);return;}const edit=e.target.closest('[data-edit]');if(edit){const r=recipes.find(x=>x.id===edit.dataset.edit);closeModal('detailModal');openForm(r);return;}const del=e.target.closest('[data-delete]');if(del){deleteRecipe(del.dataset.delete);return;}const options=e.target.closest('[data-options]');if(options){e.stopPropagation();openDetail(options.dataset.options);return;}const card=e.target.closest('[data-open]');if(card)openDetail(card.dataset.open);});document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal('formModal');closeModal('detailModal');}if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-open]')){e.preventDefault();openDetail(e.target.dataset.open);}});document.querySelectorAll('.modal-backdrop').forEach(el=>el.addEventListener('click',e=>{if(e.target===el)closeModal(el.id);}));$('themeToggle').addEventListener('click',()=>{document.body.classList.toggle('dark');$('themeToggle').textContent=document.body.classList.contains('dark')?'☾':'☼';});
render();
